/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'admin-app-log': RouteRecordInfo<'admin-app-log', '/admin/app/log', Record<never, never>, Record<never, never>>,
    'admin-approvals': RouteRecordInfo<'admin-approvals', '/admin/approvals', Record<never, never>, Record<never, never>>,
    'admin-contactus': RouteRecordInfo<'admin-contactus', '/admin/contactus', Record<never, never>, Record<never, never>>,
    'admin-document-numbers': RouteRecordInfo<'admin-document-numbers', '/admin/document/numbers', Record<never, never>, Record<never, never>>,
    'admin-histories': RouteRecordInfo<'admin-histories', '/admin/histories', Record<never, never>, Record<never, never>>,
    'admin-letterhead': RouteRecordInfo<'admin-letterhead', '/admin/letterhead', Record<never, never>, Record<never, never>>,
    'admin-positions': RouteRecordInfo<'admin-positions', '/admin/positions', Record<never, never>, Record<never, never>>,
    'admin-users': RouteRecordInfo<'admin-users', '/admin/users', Record<never, never>, Record<never, never>>,
    'document-id': RouteRecordInfo<'document-id', '/document/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'document-create': RouteRecordInfo<'document-create', '/document/create', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'preview-id': RouteRecordInfo<'preview-id', '/preview/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'preview-pdf-view': RouteRecordInfo<'preview-pdf-view', '/preview/pdf-view', Record<never, never>, Record<never, never>>,
    'profile': RouteRecordInfo<'profile', '/profile', Record<never, never>, Record<never, never>>,
    'reguler-authorization': RouteRecordInfo<'reguler-authorization', '/reguler/authorization', Record<never, never>, Record<never, never>>,
    'reguler-booking': RouteRecordInfo<'reguler-booking', '/reguler/booking', Record<never, never>, Record<never, never>>,
    'reguler-bookmark': RouteRecordInfo<'reguler-bookmark', '/reguler/bookmark', Record<never, never>, Record<never, never>>,
    'reguler-complete': RouteRecordInfo<'reguler-complete', '/reguler/complete', Record<never, never>, Record<never, never>>,
    'reguler-dashboard': RouteRecordInfo<'reguler-dashboard', '/reguler/dashboard', Record<never, never>, Record<never, never>>,
    'reguler-draft': RouteRecordInfo<'reguler-draft', '/reguler/draft', Record<never, never>, Record<never, never>>,
    'reguler-inbox': RouteRecordInfo<'reguler-inbox', '/reguler/inbox', Record<never, never>, Record<never, never>>,
    'reguler-preview': RouteRecordInfo<'reguler-preview', '/reguler/preview', Record<never, never>, Record<never, never>>,
    'reguler-progress': RouteRecordInfo<'reguler-progress', '/reguler/progress', Record<never, never>, Record<never, never>>,
    'reguler-rejected': RouteRecordInfo<'reguler-rejected', '/reguler/rejected', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
  }
}
